BUILD.md, cynthion/python/pyproject.toml
This commit also adds brief build instructions for the repo.
=> repo: fix cynthion package pip install

cynthion/python/src/selftest/gateware.py
Fixes instantiation after changes in greatscottgadgets/luna#233.
=> selftest.gateware: Fix HyperRAM instantiation

cynthion/python/src/selftest/gateware.py, cynthion/python/src/selftest/host.py
Previous PR #63 was merged without a proper fix.
=> selftest.gateware: Fix HyperRAM reads in comb domain

cynthion/python/src/gateware/soc/top.py
=> soc: use explicit phy name rather than platform.default_usb_connection

cynthion/python/src/gateware/analyzer/top.py
This is needed due to the recent addition of the `claim` signal in LUNA's `RequestHandlerInterface`.
=> gateware.analyzer: Fix vendor request handler

firmware/moondancer/Cargo.toml, firmware/moondancer/src/gcp/moondancer.rs, firmware/moondancer/src/util.rs
Accidentally left ladybug switched on.
=> firmware: disable ladybug debugging by default

cynthion/python/src/gateware/analyzer/top.py
Adds descriptors to analyzer gateware for Windows compatibility.
Depends on:
- https://github.com/greatscottgadgets/python-usb-protocol/pull/41
- https://github.com/greatscottgadgets/luna/pull/251
=> Add Microsoft OS 1.0 descriptors to analyzer gateware

cynthion/python/src/gateware/analyzer/top.py
As per https://github.com/greatscottgadgets/apollo/pull/60
=> Add USBDevice property to Microsoft descriptors

cynthion/python/src/commands/cli.py
=> cli: extend argument parsing to fix new apollo commands

.github/workflows/python.yml, cynthion/python/src/gateware/analyzer/analyzer.py
With this change, the Record being passed by the test here does not match the layout specified in `ULPIInterface`, but it matches what LUNA actually expects, and what is supplied by other gateware.
=> Fix analyzer unit tests

CHANGELOG.md, docs/source/developer/soc_firmware_compilation.rst, docs/source/hardware/cli.rst, firmware/ladybug/CHANGELOG.md, firmware/ladybug/Cargo.toml, firmware/libgreat/CHANGELOG.md, firmware/libgreat/Cargo.toml, firmware/lunasoc-hal/CHANGELOG.md, firmware/lunasoc-hal/Cargo.toml, firmware/moondancer-pac/CHANGELOG.md, firmware/moondancer-pac/Cargo.toml, firmware/moondancer/CHANGELOG.md, firmware/moondancer/Cargo.toml, firmware/smolusb/CHANGELOG.md, firmware/smolusb/Cargo.toml
=> Release 0.1.1

cynthion/python/src/gateware/analyzer/fifo.py
Also fixes problems in simulation when registering the stream output of the analyzer.
=> gateware.analyzer: fix CDC in StreamSyncUsbConverter

cynthion/python/src/commands/cynthion_setup.py
=> cli: Call sudo if needed in cynthion setup command.

cynthion/python/src/gateware/analyzer/analyzer.py
Reverts greatscottgadgets/cynthion#145
=> Revert "Add registers in analyzer stream output to improve timing."

cynthion/python/src/gateware/analyzer/analyzer.py, cynthion/python/src/gateware/analyzer/fifo.py, cynthion/python/src/gateware/analyzer/top.py
Previous attempts were not working properly.
=> gateware.analyzer: fix CDC, add special AsyncFIFO with read domain reset

cynthion/python/pyproject.toml, cynthion/python/src/__init__.py, cynthion/python/src/commands/cli.py, cynthion/python/src/commands/cynthion_info.py, cynthion/python/src/commands/util.py
Also update dependencies to Apollo 1.1.0 and pyfwup 0.5.0.
Fix #125
Fix #142
=> cli: Use Apollo's new multi-device print_info

cynthion/python/src/commands/cli.py, cynthion/python/src/commands/cynthion_setup.py
=> cli: Don't require device to create udev rule

cynthion/rust/Cargo.toml, firmware/ladybug/Cargo.toml, firmware/lunasoc-hal/src/usb.rs, firmware/moondancer/.cargo/cynthion.sh, firmware/moondancer/Cargo.toml, firmware/moondancer/src/debug.rs, firmware/moondancer/src/gcp/moondancer.rs, firmware/smolusb/src/control.rs, firmware/smolusb/src/traits.rs
This PR:
* Fixes a subtle bug with the USB HAL driver when sending a ZLP.
* Adds moondancer firmware support for: https://github.com/greatscottgadgets/facedancer/pull/115
Depends on: https://github.com/greatscottgadgets/facedancer/pull/115
---
Closes #71
Closes #134
Closes #156
=>  Fix ZLP bug on Facedancer CONTROL IN transfers

docs/source/getting_started_facedancer.rst, docs/source/getting_started_packetry.rst, docs/source/getting_started_usbproxy.rst
This addresses some of the suggestions raised in #177 
Rendered: https://cynthion--190.org.readthedocs.build/en/190/
=> Docs improvements

cynthion/python/src/gateware/analyzer/top.py
Hello, just a small typo fix to disable DP termination in the analyzer.
=> Disable analyzer DP termination
