host/cynthion/__init__.py
host/cynthion/gateware/__init__.py
host/cynthion/gateware/platform/__init__.py
host/cynthion/gateware/platform/cynthion_r0_1.py
host/cynthion/gateware/platform/cynthion_r0_2.py
host/cynthion/gateware/platform/cynthion_r0_3.py
host/cynthion/gateware/platform/cynthion_r0_4.py
host/cynthion/gateware/platform/cynthion_r0_5.py
host/cynthion/gateware/platform/cynthion_r0_6.py
host/cynthion/gateware/platform/cynthion_r0_7.py
host/cynthion/gateware/platform/cynthion_r1_0.py
host/cynthion/gateware/platform/cynthion_r1_1.py
host/cynthion/gateware/platform/cynthion_r1_2.py

This PR adds the Amaranth/LUNA platform definitions for Cynthion gateware development, placing them in the `cynthion.gateware.platforms` module.
Also provides an `APOLLO_PLATFORMS` lookup table which will be used to support platform autodetection by a new version of the `get_appropriate_platform` function in the LUNA framework.

Add Cynthion platform definitions

---

cynthion/python/src/gateware/__init__.py
cynthion/python/src/gateware/platform/__init__.py
cynthion/python/src/gateware/platform/cynthion_r1_3.py

Copied from @mossmann's LUNA branch. Note that this is actually identical to the 1.2 platform. In future we could avoid some duplication between platform definitions by inheriting some common properties.

Add Cynthion 1.3 platform

---

cynthion/python/src/gateware/platform/core.py
cynthion/python/src/gateware/platform/cynthion_r0_1.py
cynthion/python/src/gateware/platform/cynthion_r0_2.py
cynthion/python/src/gateware/platform/cynthion_r0_3.py
cynthion/python/src/gateware/platform/cynthion_r0_4.py
cynthion/python/src/gateware/platform/cynthion_r0_5.py
cynthion/python/src/gateware/platform/cynthion_r0_6.py
cynthion/python/src/gateware/platform/cynthion_r0_7.py
cynthion/python/src/gateware/platform/cynthion_r1_0.py
cynthion/python/src/gateware/platform/cynthion_r1_1.py
cynthion/python/src/gateware/platform/cynthion_r1_2.py
cynthion/python/src/gateware/platform/cynthion_r1_3.py

This PR creates a new `CynthionPlatform` class that gathers common methods and attributes and serves as a foundation for all Cynthion boards.
`CynthionPlatform` also adds support for adding custom, board-specific fragments.
A common `pseudo_power_supply_fragment` is added to wire the pseudo power supply pins to the power rails.

Add Cynthion base class and support for platform-specific fragments

---

cynthion/python/src/gateware/platform/cynthion_r0_7.py
cynthion/python/src/gateware/platform/cynthion_r1_0.py
cynthion/python/src/gateware/platform/cynthion_r1_1.py
cynthion/python/src/gateware/platform/cynthion_r1_2.py
cynthion/python/src/gateware/platform/cynthion_r1_3.py

With `r0.7` the assignment for the PMOD A pins changed.
While the `Resource` definitions were updated the change was not propogated to the `Connector` definitions.

gateware: fix platform >= 0.7 pmod a connector pins

---

cynthion/python/pyproject.toml

It's already being pulled in via `luna`.

repo: drop amaranth as a dependency for the cynthion package

---

cynthion/python/src/gateware/__init__.py
cynthion/python/src/gateware/platform/__init__.py
cynthion/python/src/gateware/platform/cynthion_r1_4.py

From the gateware's point of view, the r1.4 hardware is the same as r1.3, except that the Target-C VBUS passthrough enable signal has been inverted, and is now off by default.
The diff between the r1.3 and r1.4 platform definitions may be easier to review than the commit:
```diff
--- cynthion_r1_3.py	2024-02-06 18:42:43.365952807 +0000
+++ cynthion_r1_4.py	2024-02-06 18:45:44.080196825 +0000
@@ -11,12 +11,12 @@
from cynthion.gateware.platform.core import CynthionPlatform
-__all__ = ["CynthionPlatformRev1D3"]
+__all__ = ["CynthionPlatformRev1D4"]
-class CynthionPlatformRev1D3(CynthionPlatform):
-    """ Board description for Cynthion r1.3 """
+class CynthionPlatformRev1D4(CynthionPlatform):
+    """ Board description for Cynthion r1.4 """
-    name        = "Cynthion r1.3"
+    name …
```

Add Cynthion r1.4 platform definition

---

Dockerfile
ci/build.sh
ci/test.sh

This should fix the `tomllib` error in Jenkins.

ci: specify python 3.11

---

cynthion/python/src/gateware/analyzer/top.py

Updates the analyzer gateware to account for the Target-C -> Target-A VBUS passthrough being off by default on r1.4.
Also document the differences between hardware revisions on this aspect.

Update analyzer gateware for compatibility with Cynthion r1.4

---

cynthion/python/pyproject.toml

This PR bumps the amaranth-stdio dependency to [4a14bb17](https://github.com/amaranth-lang/amaranth-stdio/commit/4a14bb17c2c38374dc720473ee714247e8ae6b8a)
This is the latest version that:
1. Does not pull in amaranth from git.
2.  Also works with LambdaSoC.

repo: add amaranth-stdio to python dependencies

---

BUILD.md
cynthion/python/src/gateware/soc/top.py
firmware/libgreat-rs/Cargo.toml
firmware/libgreat-rs/src/gcp.rs
firmware/libgreat-rs/src/gcp/class.rs
firmware/libgreat-rs/src/gcp/class_core.rs
firmware/lunasoc-pac/src/generated/gpioa/idr.rs
firmware/lunasoc-pac/src/generated/gpioa/moder.rs
firmware/lunasoc-pac/src/generated/gpioa/odr.rs
firmware/lunasoc-pac/src/generated/gpiob/idr.rs
firmware/lunasoc-pac/src/generated/gpiob/moder.rs
firmware/lunasoc-pac/src/generated/gpiob/odr.rs
firmware/lunasoc-pac/src/generated/leds/output.rs
firmware/lunasoc-pac/svd/lunasoc.svd
firmware/moondancer/Cargo.toml
firmware/moondancer/src/bin/moondancer.rs
firmware/moondancer/src/gcp/firmware.rs
firmware/moondancer/src/gcp/moondancer.rs
firmware/moondancer/src/gcp/selftest.rs
firmware/moondancer/src/log.rs
firmware/smolusb/Cargo.toml
firmware/smolusb/src/descriptor.rs

This PR updates zerocopy from `0.7.0-alpha.2` to `0.7.34` and removes the version pin.

Update zerocopy to 0.7.34

---

firmware/moondancer/Cargo.toml
firmware/moondancer/src/bin/moondancer.rs
firmware/smolusb/Cargo.toml

This PR updates the heapless crate to 0.8.0 and removes the version pin.

firmware: update heapless crate to 0.8.0

---

cynthion/python/src/gateware/analyzer/top.py
cynthion/python/src/gateware/platform/cynthion_r0_1.py
cynthion/python/src/gateware/platform/cynthion_r0_2.py
cynthion/python/src/gateware/platform/cynthion_r0_3.py
cynthion/python/src/gateware/platform/cynthion_r0_4.py
cynthion/python/src/gateware/platform/cynthion_r0_5.py
cynthion/python/src/gateware/platform/cynthion_r0_6.py
cynthion/python/src/gateware/platform/cynthion_r0_7.py
cynthion/python/src/gateware/platform/cynthion_r1_0.py
cynthion/python/src/gateware/platform/cynthion_r1_1.py
cynthion/python/src/gateware/platform/cynthion_r1_2.py
cynthion/python/src/gateware/platform/cynthion_r1_3.py
cynthion/python/src/gateware/platform/cynthion_r1_4.py

This PR updates the analyzer gateware's descriptors and request handling as per recent discussions.
The changes are as follows:
Device descriptor:
- Changed manufacturer string from `LUNA` to `Cynthion Project`.
- Set serial string from ECP5 configuration flash ID.
- Set bcdVersion to platform version rather than analyzer protocol version.
Interface descriptor:
- Set bInterfaceClass to 0xFF (vendor specific).
- Set bInterfaceSubclass and bInterfaceProtocol to values specified in `cynthion.shared`.
Request handler:
- Now accepts requests with the recipient as the interface, rather than the device.
Corresponding Packetry support is in https://github.com/greatscottgadgets/packetry/pull/93.

Update analyzer descriptors and request handling

---

cynthion/python/src/gateware/analyzer/top.py

Remove interface string, which was causing some request handling bugs, and isn't currently needed for anything.
Set `bInterfaceProtocol` for Apollo stub.

Analyzer descriptor fixes

---

BUILD.md
ci/build.sh
cynthion/python/README.md
cynthion/python/pyproject.toml
cynthion/python/src/__init__.py
cynthion/python/src/gateware/platform/core.py
cynthion/python/src/gateware/platform/cynthion_r0_2.py
cynthion/python/src/gateware/platform/cynthion_r0_3.py
cynthion/python/src/gateware/platform/cynthion_r0_4.py
cynthion/python/src/gateware/platform/cynthion_r0_5.py
cynthion/python/src/gateware/platform/cynthion_r0_6.py
cynthion/python/src/gateware/platform/cynthion_r0_7.py
cynthion/python/src/gateware/platform/cynthion_r1_0.py
cynthion/python/src/gateware/platform/cynthion_r1_1.py
cynthion/python/src/gateware/platform/cynthion_r1_2.py
cynthion/python/src/gateware/platform/cynthion_r1_3.py
cynthion/python/src/gateware/platform/cynthion_r1_4.py
cynthion/python/src/gateware/soc/top.py
cynthion/python/src/gateware/vendor/README.md
cynthion/python/src/gateware/vendor/amaranth_boards/__init__.py
cynthion/python/src/gateware/vendor/amaranth_boards/extensions/pmod.py
cynthion/python/src/gateware/vendor/amaranth_boards/resources/__init__.py
cynthion/python/src/gateware/vendor/amaranth_boards/resources/display.py
cynthion/python/src/gateware/vendor/amaranth_boards/resources/interface.py
cynthion/python/src/gateware/vendor/amaranth_boards/resources/memory.py
cynthion/python/src/gateware/vendor/amaranth_boards/resources/user.py

This is the companion PR to: https://github.com/greatscottgadgets/luna-soc/pull/28 (already merged)
What these two PR's do is to temporarily vendor specific commits of `amaranth-boards`, `amaranth-stdio` and `amaranth-soc` as they have no official pypi releases and are in heavy flux at this time.
| Repository                                       | Commit                                                                        |
| ------------------------------------------------ | ----------------------------------------------------------------------------- |
| https://github.com/amaranth-lang/amaranth-boards | [`aba2300`](https://github.com/amaranth-lang/amaranth-boards/commit/aba2300)  |
| https://github.com/amaranth-lang/amaranth-soc   | …

repo: vendor in amaranth_boards.extensions and amaranth_boards.resources

---

cynthion/python/src/gateware/analyzer/top.py
shared/usb.toml

This PR adds a self-test device to the analyzer gateware, which appears on the AUX port.
By default, the self-test device is enabled and will enumerate at high speed. It can be disconnected, and reconnected at other speeds, via control requests to the analyzer.
The device provides a single interrupt IN endpoint, which outputs bytes from a counter.
This feature supports hardware-in-the-loop testing of the analyzer gateware and host capture software.

Add self-test device on AUX port to analyzer gateware

---

cynthion/python/src/gateware/platform/cynthion_r0_1.py
cynthion/python/src/gateware/platform/cynthion_r0_2.py
cynthion/python/src/gateware/platform/cynthion_r0_3.py
cynthion/python/src/gateware/platform/cynthion_r0_4.py
cynthion/python/src/gateware/platform/cynthion_r0_5.py
cynthion/python/src/gateware/platform/cynthion_r0_6.py
cynthion/python/src/gateware/platform/cynthion_r0_7.py
cynthion/python/src/gateware/platform/cynthion_r1_0.py
cynthion/python/src/gateware/platform/cynthion_r1_1.py
cynthion/python/src/gateware/platform/cynthion_r1_2.py
cynthion/python/src/gateware/platform/cynthion_r1_3.py
cynthion/python/src/gateware/platform/cynthion_r1_4.py

Now that port sharing is not setup automagically, using the control port PHY by default is not ideal as it needs extra setup to work. This change switches the default to aux as it's just a standard device port, and also changes older revisions to use their host PHY to match.

gateware.platform: update default USB PHY to aux/host

---

cynthion/python/src/commands/cli.py

The Cynthion cli implementation also needed to update the command definition for `info` as well as passing the new `force_offline` arg to `ApolloDebugger`.

cli: update cli with extra bits from apollo needed for --force-offline

---

cynthion/python/pyproject.toml

This is the final outstanding dependency before we can start publishing the `cynthion` package to PyPI! 🎉

python: update apollo_fpga dependency to released version

---

cynthion/rust/src/shared.rs
firmware/moondancer/examples/bulk_speed_test.rs
firmware/moondancer/examples/usb_hal.rs
firmware/moondancer/src/bin/moondancer.rs
firmware/moondancer/src/usb.rs
shared/usb.toml

For consistency with USB analyzer:
* `bProductString: "Facedancer"`
* `bManufacturerString: "Cynthion Project"`

firmware: update moondancer product string to 'Facedancer'

---

cynthion/python/src/gateware/analyzer/analyzer.py
shared/usb.toml

This PR adds timestamping to the analyzer stream, along with the basic mechanism for non-packet events, used to support timestamp rollovers.
- Bumps protocol version to `0x01`.
- Should be merged together with:
https://github.com/greatscottgadgets/packetry/pull/108
- The two PRs can be tested together via:
https://github.com/greatscottgadgets/cynthion-analyzer/pull/7.
Analyzer unit tests have been updated to test the new features.
Closes #50.

Add timestamping to analyzer

---

cynthion/python/src/gateware/analyzer/analyzer.py
cynthion/python/src/gateware/analyzer/fifo.py
cynthion/python/src/gateware/analyzer/top.py

This PR is stacked on #104 and tries to add HyperRAM buffering to the analyzer.
The code is taken from [this branch](https://github.com/mndza/cynthion-analyzer/tree/analyzer-refactor) by @mndza. The integration has been adapted to apply on top of #104, with some additional testing and verification. The `Stream16to8`, `StreamFIFO` and `HyperRAMPacketFIFO` modules are taken unmodified from that branch, and were known to work there.
I have broken down the changes into stages to help isolate the remaining issues. Tests pass at all but the final two steps.
1. Remove a couple of confusing and unused signals. :heavy_check_mark: 
2. Simplify and improve the `USBAnalyzer` unit tests. :heavy_check_mark: 
3. Use a 16-bit read port for the FIFO, followed by a `Stream16to8` conversion. …

Add HyperRAM buffering to analyzer

---

cynthion/python/src/commands/cynthion_run.py

Fixes a permission error on Windows, due to opening a second handle to the same USB device.
Tested on Windows 10.

Close existing Apollo device before running selftest

---

cynthion/python/src/gateware/analyzer/analyzer.py

This is a temporary fix until we find out the root cause of the problem.

gateware.analyzer: avoid analyzer device falling off USB bus

---

docs/requirements.txt
docs/source/conf.py
docs/source/developer/introduction.rst
docs/source/getting_started.rst

* Add docs for checking out the cynthion repo on Windows
* Update `cynthion info` output in the *Getting Started* section.
* Document the requirement to install libusb on macOS
---
Closes #132

Documentation update

---

cynthion/python/src/commands/util.py

This avoids a minor indication bug (https://github.com/greatscottgadgets/apollo/issues/108) and also avoids importing `apollo_fpga.commands.cli` which perhaps shouldn't be a public API.

cli: Use force_fpga_offline() to take FPGA offline

---

cynthion/python/src/gateware/analyzer/fifo.py
cynthion/python/src/gateware/analyzer/top.py

Fix the stop condition for final word during read bursts.

gateware.analyzer.HyperRAMPacketFIFO: fix consumer blocking FIFO writes

---

cynthion/python/src/commands/cynthion_flash.py
cynthion/python/src/commands/cynthion_run.py
docs/source/getting_started_facedancer.rst
docs/source/getting_started_usbproxy.rst

Doc update and a simple veto on doing a cynthion run or flash of the Facedancer bitstream & firmware.

Update docs & cli to help prevent folk from trying to run Facedancer on Windows.

---

docs/source/hardware/device_overview.rst
docs/source/index.rst
docs/source/project_description.rst

* reduce pages to singular focus
* clarify information per page via side menu descriptions

documentation updates

---

cynthion/python/src/commands/util.py

Apollo firmware hardware detection only works for Cynthion hardware revisions `>=r0.6`.
This PR will abort any requested update process and display a helpful message.

Dont flash unsupported firmware.

---

cynthion/rust/Cargo.toml
firmware/ladybug/Cargo.toml
firmware/lunasoc-hal/src/usb.rs
firmware/moondancer/.cargo/cynthion.sh
firmware/moondancer/Cargo.toml
firmware/moondancer/src/debug.rs
firmware/moondancer/src/gcp/moondancer.rs
firmware/smolusb/src/control.rs
firmware/smolusb/src/traits.rs

This PR fixes a few things:
* Refactor `clear_feature_endpoint_halt` arguments in the USB HAL driver to match stall arguments.
* Add a `clear_feature_endpoint_halt` verb to the Moondancer GCP class.
* Compiler warnings on the latest rustc release.
* Incorrect reference to a Makefile target.
* Fixes a compiler error when ladybug is enabled.
Depends on: https://github.com/greatscottgadgets/facedancer/pull/106

Improve USBProxy reliability

---

docs/source/index.rst

docs: fix Tutorials capitalization

---

firmware/moondancer-pac/CHANGELOG.md
firmware/moondancer-pac/Cargo.toml

All previous versions of the critical-section crate have been pulled from crates.io due to a soundness issue. This PR bumps us to the current release which contains the fixes.
---
Closes #198

pac: bump critical-section crate to version =1.2.0

---

docs/source/getting_started_packetry.rst
docs/source/index.rst
docs/source/tutorials/emulation.rst
docs/source/tutorials/usb_analysis.rst

This PR moves the tutorials from `/docs/source` to `/docs/source/tutorials`.

docs: move tutorials to their own subdirectory

---

Dockerfile

Fixes the issue causing #203 to fail.

Pin oss-cad-suite version to 2024-11-01 for CI

---

firmware/lunasoc-hal/src/usb.rs
firmware/moondancer/src/gcp/moondancer.rs

This PR is part of:
* https://github.com/greatscottgadgets/luna-soc/pull/35
* https://github.com/greatscottgadgets/facedancer/pull/124
---
This PR adds some supporting machinery to fix the Facedancer alternate interface unit tests:
* When connecting/disconnecting a USB device pre-existing endpoints from a previous session may still be primed.
* After moondancer receives a set interface request, the underlying eptri ep_out gateware pid state has a 50% chance of being incorrect.
* Added a moondancer method to re-enable the OUT interface for packet reception.

Fix facedancer unittests

---

firmware/moondancer/src/gcp/moondancer.rs

When usb packets are sent from facedancer on the control endpoint the data was not packetized according to the configured max_packet_size for endpoint 0.
This PR uses the correct usb hal method to specify the desired `max_packet_size` for endpoint 0.
--- 
Closes https://github.com/greatscottgadgets/facedancer/issues/156

firmware: use correct usb hal write function for facedancer control endpoint

---

cynthion/python/Makefile

While YoWASP support has been integrated into the luna `top_level_cli` the Makefile for Cynthion's gateware assets only checks for Yosys. This PR will extend that check to also support YoWASP.

build: add yowasp support to the 'detect-fpga-toolchain' Makefile rule

---

cynthion/python/examples/tutorials/gateware-usb-device-02.py
cynthion/python/examples/tutorials/gateware-usb-device-03.py
cynthion/python/examples/tutorials/gateware-usb-device-04.py
cynthion/python/src/gateware/analyzer/top.py
docs/source/tutorials/gateware_usb_device_02.rst
docs/source/tutorials/gateware_usb_device_03.rst

support for non-contiguous string descriptor indexes in block RAM was fixed in greatscottgadgets/luna#292

gateware: use block RAM again for string descriptors
